### ISSUE TITLE
Misc. issues 10/10/2021

### ISSUE THREAD

**Issue by PesiTheWizard** [townteki/townsquare#1116]
- [x] #1118
Most likely an onCardBountyAdded vs onCardBountyChanged issue

- [x] After using Quick-draw handgun, the original cheater can now punish the freshly-cheatin hand.

- [x] #1119

**Comment by mmeldo** [comment]
The Quickdraw handgun allowing to play cheatin against swapped hand was conscious decision. The client does not strictly forbid everything, that would be too much and difficult to implement. There are still rules that player should follow (even though client allows it) and it is specifically written on the card, so I decided not to implement the restriction. If anyone wants, feel free but since this is will be legacy, I am not going to.
