### ISSUE TITLE
Action card ability usage is not reset when leaving play

### ISSUE THREAD

**Issue by PesiTheWizard** [townteki/townsquare#1212]
**Card**
Incubation

**Describe the bug**
After a dude has discarded Incubation from themselves, it can't be played from hand during the same turn; even on other dudes. (this can happen with Jia Mein (Exp.1))

**Additional context**
I suspect either the "!this.parent" part is keeping it from being played if it had a parent at the start of the turn/phase, or it isn't detatched properly; or the parent's use of the granted ability is interfering with it.

**Comment by mmeldo** [comment]
The problem is not with Incubation itself. Any action card that is played, then manually discarded and put into hand (or put into hand directly) cannot be played again because the usage counter was not reset. You can see the ability usage icon (hourglass) next to the grayed out "Use ability" action.
Interestingly, if you then move the card from hand to discard and back the usage counter is reset and card can be played. 
Therefore I believe here we will just have to make sure the usage counter is rest properly when leaving play.
